# 

GET http://127.0.0.1:3001/spotify/me
Authorization: Bearer BQCReQOtCRThOMagZWtf3H2rhaZpfF5vQBZKBjmNP7MtNaCrhVqbn1KyH9cw406EOsDXBfaOdWGn2tB9Z26krXUHjwIr2FBY2NRKHa6E-Rv1R5cqFdA-v2QRMvpB6_bQlGrf_UBFyIn7vr83BB85Yz5xML8sRc-Jb4HaUTVbERNzhQ-5KQZsTGpIjfkwPfJbQ3a9uUT6pskL4RaDGAnppUkxZ3GKjgzGYRV23GrZRbMiquOpjnrfR3j0hB77jZPiQP_nhuA