# 

GET http://127.0.0.1:3001/spotify/summary
Authorization: Bearer BQAb_1miUQpDzP9PnV7OwsP91_DPwCSGSV61FgsJEVW_v1u955Zfl-BAH4qrdiyRxoLa8kzt5g10sceWndkvjCPMAC3ymq32tJDl2HIt_UD0gpM6arPPhev2uAOOL34zBDNhF99qTbB0a3Di-4c9hEw2xocDTzULlGJJdlxzh1UZ8lRhgUSd7MCk4uZ2ALyEN_rXg4gm0gX99zCEcL-fogr8AG_QOvr5fYj_XtGvYc8t7xEufIEOEQScX07pJQe4M1AQgw8&refresh_token=AQDKlhJ8e_ndYC5m6Kvf6U9XxUNa65KvrRBKPmf-hwLC0gnCcu0YTdp6Jw8WPWay5p5XADjt-Zst34ehngE_TirWCNKp9g7L2kcHU_2D-Y858OsoWl0KRtoeysiBBGG0Nik&expires_in=3600