# 

GET http://127.0.0.1:3001/spotify/top-tracks
Authorization: Bearer BQCwetiIMvmdBwiRGU2E_4c9Mw6ep1anxTzRITSIQ5lNLmimEZYN-GXCeqYbiDQW6yvemMyoa6vgAQ8eDv_H60SejF64Gvk9OZKjPy5TWoLYHs77grcxtdzpjeUCI6yYwg_A0ZiV9w-3GmZqk3v7kSWXzavq2GxReDYaXZhB-Ny6LSIX3AkvNTGSXnvPTOLj-u-Q20QBKGQHw4OgKGQAferGhUlArsKgJJIMZSUqatPScvtDEUeu2eXFHJ-Se-gW5nJICNA&refresh_token=AQDkcOmDcjLwXOAG-Ct2MGZz87U5XWjOq0J1EImdP3O6Tt_HnG5V1-txeNd3tHFSfgoM9Rg2yg-e4mt31JVPFnr4Euz64qkF2_UZpRVqLD0pBylc0EWHuP7D8q6xC5gx11c&expires_in=3600